### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NightRaidGamer** [Mattiwatti/PPLKiller#20]
could you add support to remove this please? I'm referring to Secure (IUM)

![Sem título](https://user-images.githubusercontent.com/87019952/144279317-a3927a6e-3104-4aec-a9af-8b2671cf9dfa.png)

**Comment by Mattiwatti** [comment]
You can do this yourself by setting DWORD `HyperVVirtualizationBasedSecurityOptOut` to `0x1` in `HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard`.
