### ISSUE TITLE
Question regarding PatchGuard check

### ISSUE THREAD

**Issue by diejozef** [Mattiwatti/PPLKiller#21]
Hi,

You mentioned that starting with 10.0.18362.0, PatchGuard will check protection level integrity on system processes. Can you give me a bit of insight on how the kernel does this? Does it have to do with PEAuth.sys? Some references to the code that causes the bugcheck would be very much appreciated!

Thank you in advance!

**Comment by Mattiwatti** [comment]
Thanks, this has been fixed now.

**Comment by Mattiwatti** [comment]
Apologies, I had two tabs with GitHub issues open and closed the wrong one.

An in-depth explanation of how PatchGuard does these checks is a bit much for me to write here (besides, I can hardly claim to know everything about it), but you may find the following links useful (from oldest to newest):

- Uninformed articles on PatchGuard [v1](http://uninformed.org/index.cgi?v=3&a=3&t=pdf), [v2](http://www.uninformed.org/?v=6&a=1&t=pdf) and [v3](http://uninformed.org/index.cgi?v=8&a=5&t=pdf) by Skywing
- [Analysis of PatchGuard by Luc Reginato of Tetrane](https://blog.tetrane.com/downloads/Tetrane_PatchGuard_Analysis_RS4_v1.00.pdf)

Neither `PEAuth.sys` nor `mssecflt.sys` (the other Microsoft driver associated with PatchGuard) is (directly) involved in these checks as far as I know. You can verify this by disabling both services (`sc config <drivername> start= disabled`), rebooting, loading PPLKiller or some other driver that runs afoul of PatchGuard, and seeing that the bugcheck will still occur after some time.

**Comment by diejozef** [comment]
Thank you very much for your fast answer and the resources you provided, I'll dig into the workings of PatchGuard. I was looking for info related to the specific change in that Windows version that started to check for process protection and bugcheck when tampered with. I heard something that a driver that went through the signing process of Microsoft can still tamper with protected processes this way but I don't see how PatchGuard could differentiate between drivers that access the EPROCESS structure of a process. Do you happen to have any info on that?

**Comment by Mattiwatti** [comment]
> I heard something that a driver that went through the signing process of Microsoft can still tamper with protected processes this way

What direction is this tampering going in: disabling protection or enabling it on a previously non-protected process? If the former, I would say this is not supposed to be possible, assuming the target is a system process (perhaps excepting ELAM drivers - I doubt it would matter but I haven't verified this). Do you have any more details?

> I don't see how PatchGuard could differentiate between drivers that access the EPROCESS structure of a process

Me neither. Or rather, I guess I see how it _could_, but I don't believe PatchGuard keeps track of this information generally speaking, so this would be an exception to the rule.

**Comment by aschauer1** [comment]
It's about disabling protection of a protected process. I think I'll handle this (the stuff about being able to remove protection without PatchGuard BugCheck) as hearsay and expect to receive a BugCheck 0x109 with Parameter4 = `0x1F` (Modification of a protected process) even when the flag was disabled by a driver signed by Microsoft. The only thing that I can think of is restoring the protection fast enough to go unnoticed by PatchGuard but I don't think that's a reliable solution. 

I think you can close this one, thank you for all your help!
