### ISSUE TITLE
Windows 7 system process

### ISSUE THREAD

**Issue by kyrox02** [Mattiwatti/PPLKiller#5]
i would like to ask if its possible to bypass protected in kernel

![dvs](https://user-images.githubusercontent.com/27238585/32791432-b18e8fe6-c969-11e7-8e09-7560b35cba87.png)

win7 x64

**Comment by Mattiwatti** [comment]
Yes, this is possible. May I ask what you hope to achieve by doing this? Not that I'm opposed to doing useless things per se, but if there is a real use for unprotecting the system process I'm unaware of then I will add it to the README. As far as I know there isn't any.

**Comment by kyrox02** [comment]
just want make sure everything accessible without any rejection

**Comment by Mattiwatti** [comment]
_What_ specifically should be accessible from _where_ that isn't currently? I'm pretty sure disabling process protection on the system process isn't going to solve whatever issue you're trying to solve.

Anyway, here's how to do it:
- Open the project properties in Visual Studio, go to Driver Settings and set the target version to Windows 7.
- Open `procinfo.h` and add the following struct:
```C++
typedef struct _EPROCESS_FLAGS2_WIN7
{
  union
  {
    ULONG Flags2;
    struct
    {
      UCHAR JobNotReallyActive : 1;
      UCHAR AccountingFolded : 1;
      UCHAR NewProcessReported : 1;
      UCHAR ExitProcessReported : 1;
      UCHAR ReportCommitChanges : 1;
      UCHAR LastReportMemory : 1;
      UCHAR ReportPhysicalPageChanges : 1;
      UCHAR HandleTableRundown : 1;
      UCHAR NeedsHandleRundown : 1;
      UCHAR RefTraceEnabled : 1;
      UCHAR NumaAware : 1;
      UCHAR ProtectedProcess : 1;
      UCHAR DefaultPagePriority : 3;
      UCHAR PrimaryTokenFrozen : 1;
      UCHAR ProcessVerifierTarget : 1;
      UCHAR StackRandomizationDisabled : 1;
      UCHAR AffinityPermanent : 1;
      UCHAR AffinityUpdateEnable : 1;
      UCHAR PropagateNode : 1;
      UCHAR ExplicitAffinity : 1;
      UCHAR Spare1 : 1;
      UCHAR ForceRelocateImages : 1;
      UCHAR DisallowStrippedImages : 1;
      UCHAR LowVaAccessible : 1;
    } s;
  } u;
} EPROCESS_FLAGS2_WIN7, *PEPROCESS_FLAGS2_WIN7;
```
- Open `main.cpp` and replace `DriverEntry` with this:
```C++
NTSTATUS
DriverEntry(
  _In_ PDRIVER_OBJECT DriverObject,
  _In_ PUNICODE_STRING RegistryPath
  )
{
  PAGED_CODE();

  UNREFERENCED_PARAMETER(RegistryPath);

  PEPROCESS Process;
  PsLookupProcessByProcessId(ULongToHandle(4), &Process);
  PEPROCESS_FLAGS2_WIN7 Flags = reinterpret_cast<PEPROCESS_FLAGS2_WIN7>(reinterpret_cast<PUCHAR>(Process) + 0x43C);
  Flags->u.s.ProtectedProcess = 0;
  ObfDereferenceObject(Process);

  DriverObject->DriverUnload = DriverUnload;
  return STATUS_SUCCESS;
}
```

**Comment by kyrox02** [comment]
thank you solved
